backend:
    name: git-gateway
    branch: master

media_folder: static/img
public_folder: /img

collections:
    - name: "blog"
      label: "Blog"
      format: "json"
      folder: "assets/content/blog"
      create: true
      slug: "{{slug}}"
      editor:
          preview: true
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }
          - {
                label: "Publish Date",
                name: "date",
                widget: "datetime",
                dateFormat: "DD.MM.YYYY",
            }
          - { label: "Body", name: "body", widget: "markdown" }

    - name: "socialIcons"
      label: "Social Icons"
      format: "json"
      create: true
      folder: "assets/content/socialIcons"
      fields:
          - { label: "Link", name: "link", widget: "string" }
          - { label: "Icon", name: "image", widget: "image" }

    - name: "pages"
      label: "Pages"
      files:
          - label: "About Page"
            name: "about"
            file: "site/content/about.yml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro, name: intro, widget: markdown }
                - label: Team
                  name: team
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Position, name: position, widget: string }
                      - { label: Photo, name: photo, widget: image }
          - label: "Locations Page"
            name: "locations"
            file: "site/content/locations.yml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro, name: intro, widget: markdown }
                - label: Locations
                  name: locations
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Address, name: address, widget: string }
